# @baseUrl = http://localhost:8080
@baseUrl = http://104.40.229.73
@remoteBaseUrl = https://julesdesmet.be
@imagePath = /Users/oliwierzgorniak/Pictures/igi.png


GET {{remoteBaseUrl}}/drupal/session/token HTTP/1.1

###

POST {{baseUrl}}/jsonapi/node/story/field_picture HTTP/1.1
Content-Type: application/octet-stream
Accept: application/vnd.api+json
Content-Disposition: file; filename="igi.png"

< {{imagePath}}

###
POST http://localhost:8080/jsonapi/node/story HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "node--story",
    "attributes": {
      "title": "8",
      "field_username": "oliwier",
      "field_description": "Playing cards"
    },
    "relationships": {
      "field_picture": {
        "data": {
          "type": "file--file",
          "id": "13b93af5-7384-4e2d-8769-83ba0310f08a"
        }
      }
    }
  }
}

###

GET http://localhost:8080/jsonapi/node/story?include=field_pciture HTTP/1.1

###

GET {{remoteBaseUrl}}/drupal/jsonapi HTTP/1.1