# https://www.drupal.org/node/2715637

parameters:
  cors.config:
    enabled: true
    # Specify allowed headers, like 'x-allowed-header'.
    allowedHeaders:
      [
        "x-csrf-token",
        "authorization",
        "content-type",
        "accept",
        "origin",
        "x-requested-with",
        "content-disposition",
      ]
    # Specify allowed request methods, specify ['*'] to allow all possible ones.
    allowedMethods: ["*"]
    # Configure requests allowed from specific origins.
    allowedOrigins: ["http://localhost:4321"]
    # Sets the Access-Control-Expose-Headers header.
    exposedHeaders: []
    # Sets the Access-Control-Max-Age header.
    maxAge: 1000
    # Sets the Access-Control-Allow-Credentials header.
    supportsCredentials: true
